language: ruby

services:
  - mysql
  - postgresql

rvm:
  - 1.9.3
  - 2.0.0

gemfile:
  - $REDMINE_PATH/Gemfile

env:
  - REDMINE_VER=2.3.3 DB=mysql
  - REDMINE_VER=2.3.4 DB=mysql
  - REDMINE_VER=2.4.6 DB=mysql
  - REDMINE_VER=2.5.2 DB=mysql
  - REDMINE_VER=2.3.3 DB=postgresql
  - REDMINE_VER=2.3.4 DB=postgresql
  - REDMINE_VER=2.4.6 DB=postgresql
  - REDMINE_VER=2.5.2 DB=postgresql

before_install:
  - export PLUGIN_NAME=redmine_customize
  - export REDMINE_PATH=$HOME/redmine
  - svn co http://svn.redmine.org/redmine/tags/$REDMINE_VER $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH
  - git clone --depth=1 https://github.com/Undev/redmine__select2.git $REDMINE_PATH/plugins/redmine__select2

before_script:
  - rake db:create
  - rake db:migrate
  - rake redmine:plugins:migrate

script:
  - rake redmine:plugins:test NAME=$PLUGIN_NAME

